In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
#1.Write a Pandas program to compare the elements of two Pandas series. Sample Series [4,65,436,3,9], [7,0,3,897,9]
#using comparison operator 
series1 = pd.Series([4, 65, 436, 3, 9])
series2 = pd.Series([7, 0, 3, 897, 9])

comparison = series1 == series2

print(comparison)

0    False
1    False
2    False
3    False
4     True
dtype: bool

In [3]:
#2.	Write a Pandas program to add, subtract, multiply and divide two Pandas series. Sample Series: [2,4,6,8,14], [1,3,5,7,9]
series1 = pd.Series([2, 4, 6, 8, 14])
series2 = pd.Series([1, 3, 5, 7, 9])

# Addition
addition = series1 + series2
print("Addition:")
print(addition)

# Subtraction
subtraction = series1 - series2
print("\nSubtraction:")
print(subtraction)

# Multiplication
multiplication = series1 * series2
print("\nMultiplication:")
print(multiplication)

# Division
division = series1 / series2
print("\nDivision:")
print(division)

Addition:
0     3
1     7
2    11
3    15
4    23
dtype: int64

Subtraction:
0    1
1    1
2    1
3    1
4    5
dtype: int64

Multiplication:
0      2
1     12
2     30
3     56
4    126
dtype: int64

Division:
0    2.000000
1    1.333333
2    1.200000
3    1.142857
4    1.555556
dtype: float64

In [4]:
#3.	Write a Pandas program to convert a dictionary to a Pandas series. Sample dictionary: dictionary1 = {‘Josh’: 24, ‘Sam’: 36, ‘Peace’: 19, ‘Charles’: 65, ‘Tom’: 44}
dictionary1 = {'Josh': 24, 'Sam': 36, 'Peace': 19, 'Charles': 65, 'Tom': 44}
series = pd.Series(dictionary1)
print(series)

Josh       24
Sam        36
Peace      19
Charles    65
Tom        44
dtype: int64

In [5]:
#4.	Write a Pandas program to convert a given series to an array.Sample series: [‘Love’, 800, ‘Joy’, 789.9, ‘Peace’, True]
series = pd.Series(['Love', 800, 'Joy', 789.9, 'Peace', True])

array = np.array(series)

print(array)

['Love' 800 'Joy' 789.9 'Peace' True]

In [9]:

df = pd.read_csv('AfricaCupofNationsMatches.csv')

# Creating a Series from the HomeTeamGoals column
series = df['HomeTeamGoals']

# Finding the most frequent value
most_frequent = series.value_counts().idxmax()

print("Most frequent value:", most_frequent)

# Replacing other values with 'Other'
series[series != most_frequent] = 'Other'

# Displaying the modified Series
print(series)

Most frequent value: 1.0
0        1.0
1      Other
2      Other
3      Other
4        1.0
       ...
617    Other
618      1.0
619    Other
620    Other
621    Other
Name: HomeTeamGoals, Length: 622, dtype: object

C:\Users\HP\AppData\Local\Temp\ipykernel_9652\880405317.py:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  series[series != most_frequent] = 'Other'

In [10]:
#1.	Write a Pandas program to read the given csv file.
df= pd.read_csv('AfricaCupofNationsMatches.csv')
df

,Year,Date,Time,HomeTeam,AwayTeam,HomeTeamGoals,AwayTeamGoals,Stage,SpecialWinConditions,Stadium,City,Attendance
0,1957,10-Feb-57,NaN,Sudan,Egypt,1.0,2.0,Semifinals,NaN,Municipal Stadium,Khartoum,30000.0
1,1957,10-Feb-57,NaN,Ethiopia,South Africa,NaN,NaN,Semifinals,Ethiopia wins due to disqualification of othe...,NaN,NaN,NaN
2,1957,16-Feb-57,NaN,Egypt,Ethiopia,4.0,0.0,Final,NaN,Municipal Stadium,Khartoum,30000.0
3,1959,22-May-59,NaN,Egypt,Ethiopia,4.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,30000.0
4,1959,25-May-59,NaN,Sudan,Ethiopia,1.0,0.0,Final Tournament,NaN,Prince Farouk Stadium,Cairo,20000.0
...,...,...,...,...,...,...,...,...,...,...,...,...
617,2019,11 July 2019 (2019-07-11),21:00,Madagascar,Tunisia,0.0,3.0,Quarter-finals,NaN,Al Salam Stadium,Cairo,7568.0
618,2019,14 July 2019 (2019-07-14),18:00,Senegal,Tunisia,1.0,0.0,Semi-finals,win after extra time,30 June Stadium,Cairo,9143.0
619,2019,14 July 2019 (2019-07-14),21:00,Algeria,Nigeria,2.0,1.0,Semi-finals,NaN,Cairo International Stadium,Cairo,49775.0
620,2019,17 July 2019 (2019-07-17),21:00,Tunisia,Nigeria,0.0,1.0,Third place play-off,NaN,Al Salam Stadium,Cairo,6340.0
621,2019,19 July 2019 (2019-07-19),21:00,Senegal,Algeria,0.0,1.0,Final,NaN,Cairo International Stadium,Cairo,75000.0

In [11]:
#2.	Write a Pandas program to get the first 7 rows of your data frame.
first_7_rows = df.head(7)
print(first_7_rows)

   Year      Date  Time    HomeTeam       AwayTeam  HomeTeamGoals  \
0  1957  10-Feb-57   NaN     Sudan           Egypt            1.0
1  1957  10-Feb-57   NaN  Ethiopia    South Africa            NaN
2  1957  16-Feb-57   NaN     Egypt        Ethiopia            4.0
3  1959  22-May-59   NaN      Egypt       Ethiopia            4.0
4  1959  25-May-59   NaN     Sudan        Ethiopia            1.0
5  1959  29-May-59   NaN      Egypt          Sudan            2.0
6  1962  14-Jan-62   NaN  Ethiopia         Tunisia            4.0

   AwayTeamGoals             Stage  \
0            2.0        Semifinals
1            NaN        Semifinals
2            0.0             Final
3            0.0  Final Tournament
4            0.0  Final Tournament
5            1.0  Final Tournament
6            2.0        Semifinals

                                SpecialWinConditions                 Stadium  \
0                                                NaN       Municipal Stadium
1  Ethiopia  wins due to disqualification of othe...                     NaN
2                                                NaN       Municipal Stadium
3                                                NaN   Prince Farouk Stadium
4                                                NaN   Prince Farouk Stadium
5                                                NaN   Prince Farouk Stadium
6                                                NaN  Hailé Sélassié Stadium

           City  Attendance
0      Khartoum     30000.0
1           NaN         NaN
2      Khartoum     30000.0
3         Cairo     30000.0
4         Cairo     20000.0
5         Cairo     30000.0
6   Addis Ababa     30000.0

In [12]:
#3.	Write a Pandas program to select the ‘HomeTeam’, ‘AwayTeam’, ‘HomeTeamGoals’ and ‘AwayTeamGoals’ columns from your data frame.
selected_columns = df[['HomeTeam', 'AwayTeam', 'HomeTeamGoals', 'AwayTeamGoals']]

print(selected_columns)

        HomeTeam       AwayTeam  HomeTeamGoals  AwayTeamGoals
0         Sudan           Egypt            1.0            2.0
1      Ethiopia    South Africa            NaN            NaN
2         Egypt        Ethiopia            4.0            0.0
3          Egypt       Ethiopia            4.0            0.0
4         Sudan        Ethiopia            1.0            0.0
..           ...            ...            ...            ...
617  Madagascar         Tunisia            0.0            3.0
618     Senegal         Tunisia            1.0            0.0
619     Algeria         Nigeria            2.0            1.0
620     Tunisia         Nigeria            0.0            1.0
621     Senegal         Algeria            0.0            1.0

[622 rows x 4 columns]

In [14]:
#4.	Write a Pandas program to select the rows where Egypt appears.
egypt_rows = df[df.apply(lambda row: row.astype(str).str.contains('Egypt').any(), axis=1)]
print(egypt_rows)

     Year                         Date   Time  HomeTeam       AwayTeam  \
0    1957                     10-Feb-57    NaN   Sudan           Egypt
2    1957                     16-Feb-57    NaN   Egypt        Ethiopia
3    1959                     22-May-59    NaN    Egypt       Ethiopia
5    1959                     29-May-59    NaN    Egypt          Sudan
7    1962                     18-Jan-62    NaN    Egypt         Uganda
..    ...                           ...    ...      ...            ...
569  2017  5 February 2017 (2017-02-05)  20:00   Egypt        Cameroon
570  2019     21 June 2019 (2019-06-21)  22:00   Egypt        Zimbabwe
573  2019     26 June 2019 (2019-06-26)  22:00   Egypt        DR Congo
574  2019     30 June 2019 (2019-06-30)  21:00  Uganda           Egypt
609  2019      6 July 2019 (2019-07-06)  21:00   Egypt    South Africa

     HomeTeamGoals  AwayTeamGoals             Stage SpecialWinConditions  \
0              1.0            2.0        Semifinals                  NaN
2              4.0            0.0             Final                  NaN
3              4.0            0.0  Final Tournament                  NaN
5              2.0            1.0  Final Tournament                  NaN
7              2.0            1.0        Semifinals                  NaN
..             ...            ...               ...                  ...
569            1.0            2.0             Final                  NaN
570            1.0            0.0           Group A                  NaN
573            2.0            0.0           Group A                  NaN
574            0.0            2.0           Group A                  NaN
609            0.0            1.0       Round of 16                  NaN

                         Stadium          City  Attendance
0              Municipal Stadium      Khartoum     30000.0
2              Municipal Stadium      Khartoum     30000.0
3          Prince Farouk Stadium         Cairo     30000.0
5          Prince Farouk Stadium         Cairo     30000.0
7         Hailé Sélassié Stadium   Addis Ababa     30000.0
..                           ...           ...         ...
569            Stade de l'Amitié    Libreville         NaN
570  Cairo International Stadium         Cairo     73299.0
573  Cairo International Stadium         Cairo     74219.0
574  Cairo International Stadium         Cairo     74566.0
609  Cairo International Stadium         Cairo     75000.0

[95 rows x 12 columns]

In [15]:
#5.	Write a Pandas program to count the number of rows and columns of your data frame.
df.shape

(622, 12)

In [16]:
#6.	Write a Pandas program to select the rows where the ‘Attendance’ is missing.
attendance_missing = df[df['Attendance'].isna()]
print(attendance_missing)

     Year                         Date   Time        HomeTeam       AwayTeam  \
1    1957                     10-Feb-57    NaN      Ethiopia    South Africa
8    1962                     20-Jan-62    NaN       Tunisia          Uganda
9    1962                     21-Jan-62    NaN      Ethiopia           Egypt
10   1963                     24-Nov-63    NaN         Ghana         Tunisia
11   1963                     26-Nov-63    NaN         Ghana        Ethiopia
..    ...                           ...    ...            ...            ...
565  2017  29 January 2017 (2017-01-29)  20:00         Egypt         Morocco
566  2017  1 February 2017 (2017-02-01)  20:00  Burkina Faso           Egypt
567  2017  2 February 2017 (2017-02-02)  20:00      Cameroon           Ghana
568  2017  4 February 2017 (2017-02-04)  20:00  Burkina Faso           Ghana
569  2017  5 February 2017 (2017-02-05)  20:00         Egypt        Cameroon

     HomeTeamGoals  AwayTeamGoals                 Stage  \
1              NaN            NaN            Semifinals
8              3.0            0.0     Third place match
9              4.0            2.0                 Final
10             1.0            1.0               Group A
11             2.0            0.0               Group A
..             ...            ...                   ...
565            1.0            0.0        Quarter-finals
566            1.0            1.0           Semi-finals
567            2.0            0.0           Semi-finals
568            1.0            0.0  Third place play-off
569            1.0            2.0                 Final

                                  SpecialWinConditions  \
1    Ethiopia  wins due to disqualification of othe...
8                                                  NaN
9                                win after extra time
10                                                 NaN
11                                                 NaN
..                                                 ...
565                                                NaN
566                        Egypt win on Penalities 3-4
567                                                NaN
568                                                NaN
569                                                NaN

                    Stadium          City  Attendance
1                       NaN           NaN         NaN
8    Hailé Sélassié Stadium   Addis Ababa         NaN
9    Hailé Sélassié Stadium   Addis Ababa         NaN
10     Accra Sports Stadium         Accra         NaN
11     Accra Sports Stadium         Accra         NaN
..                      ...           ...         ...
565    Stade de Port-Gentil   Port-Gentil         NaN
566       Stade de l'Amitié    Libreville         NaN
567    Stade de Franceville   Franceville         NaN
568    Stade de Port-Gentil   Port-Gentil         NaN
569       Stade de l'Amitié    Libreville         NaN

[100 rows x 12 columns]

In [17]:
#7.	Write a Pandas program to select the rows where the ‘HomeTeamGoals’ are between 3 and 6 inclusive.
selected_rows = df[(df['HomeTeamGoals'] >= 3) & (df['HomeTeamGoals'] <= 6)]
print(selected_rows)

     Year                         Date   Time    HomeTeam     AwayTeam  \
2    1957                     16-Feb-57    NaN     Egypt      Ethiopia
3    1959                     22-May-59    NaN      Egypt     Ethiopia
6    1962                     14-Jan-62    NaN  Ethiopia       Tunisia
8    1962                     20-Jan-62    NaN   Tunisia        Uganda
9    1962                     21-Jan-62    NaN  Ethiopia         Egypt
..    ...                           ...    ...        ...          ...
553  2017  20 January 2017 (2017-01-20)  20:00   Morocco          Togo
585  2019     27 June 2019 (2019-06-27)  22:00     Kenya      Tanzania
595  2019     24 June 2019 (2019-06-24)  22:00      Mali    Mauritania
608  2019      6 July 2019 (2019-07-06)  18:00   Nigeria      Cameroon
611  2019      7 July 2019 (2019-07-07)  21:00   Algeria        Guinea

     HomeTeamGoals  AwayTeamGoals              Stage    SpecialWinConditions  \
2              4.0            0.0              Final                     NaN
3              4.0            0.0   Final Tournament                     NaN
6              4.0            2.0         Semifinals                     NaN
8              3.0            0.0  Third place match                     NaN
9              4.0            2.0              Final   win after extra time
..             ...            ...                ...                     ...
553            3.0            1.0            Group C                     NaN
585            3.0            2.0            Group C                     NaN
595            4.0            1.0            Group E                     NaN
608            3.0            2.0        Round of 16                     NaN
611            3.0            0.0        Round of 16                     NaN

                    Stadium          City  Attendance
2         Municipal Stadium      Khartoum     30000.0
3     Prince Farouk Stadium         Cairo     30000.0
6    Hailé Sélassié Stadium   Addis Ababa     30000.0
8    Hailé Sélassié Stadium   Addis Ababa         NaN
9    Hailé Sélassié Stadium   Addis Ababa         NaN
..                      ...           ...         ...
553            Stade d'Oyem          Oyem         NaN
585         30 June Stadium         Cairo      7233.0
595            Suez Stadium          Suez      6202.0
608      Alexandria Stadium    Alexandria     10000.0
611         30 June Stadium         Cairo      8205.0

[138 rows x 12 columns]

In [18]:
#8.	Write a Pandas program to change the “AwayTeamGoals” in the 3rd row to 10.
df.at[2, 'AwayTeamGoals'] = 10
print(df)

     Year                      Date   Time      HomeTeam       AwayTeam  \
0    1957                  10-Feb-57    NaN       Sudan           Egypt
1    1957                  10-Feb-57    NaN    Ethiopia    South Africa
2    1957                  16-Feb-57    NaN       Egypt        Ethiopia
3    1959                  22-May-59    NaN        Egypt       Ethiopia
4    1959                  25-May-59    NaN       Sudan        Ethiopia
..    ...                        ...    ...          ...            ...
617  2019  11 July 2019 (2019-07-11)  21:00  Madagascar         Tunisia
618  2019  14 July 2019 (2019-07-14)  18:00     Senegal         Tunisia
619  2019  14 July 2019 (2019-07-14)  21:00     Algeria         Nigeria
620  2019  17 July 2019 (2019-07-17)  21:00     Tunisia         Nigeria
621  2019  19 July 2019 (2019-07-19)  21:00     Senegal         Algeria

     HomeTeamGoals  AwayTeamGoals                 Stage  \
0              1.0            2.0            Semifinals
1              NaN            NaN            Semifinals
2              4.0           10.0                 Final
3              4.0            0.0      Final Tournament
4              1.0            0.0      Final Tournament
..             ...            ...                   ...
617            0.0            3.0        Quarter-finals
618            1.0            0.0           Semi-finals
619            2.0            1.0           Semi-finals
620            0.0            1.0  Third place play-off
621            0.0            1.0                 Final

                                  SpecialWinConditions  \
0                                                  NaN
1    Ethiopia  wins due to disqualification of othe...
2                                                  NaN
3                                                  NaN
4                                                  NaN
..                                                 ...
617                                                NaN
618                              win after extra time
619                                                NaN
620                                                NaN
621                                                NaN

                         Stadium       City  Attendance
0              Municipal Stadium   Khartoum     30000.0
1                            NaN        NaN         NaN
2              Municipal Stadium   Khartoum     30000.0
3          Prince Farouk Stadium      Cairo     30000.0
4          Prince Farouk Stadium      Cairo     20000.0
..                           ...        ...         ...
617             Al Salam Stadium      Cairo      7568.0
618              30 June Stadium      Cairo      9143.0
619  Cairo International Stadium      Cairo     49775.0
620             Al Salam Stadium      Cairo      6340.0
621  Cairo International Stadium      Cairo     75000.0

[622 rows x 12 columns]